main.name = "R1CK"
main.lang = "de"
main.whitelist = [
 "Net-Internal",
 "ANOTHER_EXAMPLE_NETWORK",
 "fo:od:ba:be:fo:od",
 "fo:od:ba",
]
main.plugins.grid.enabled = true
main.plugins.grid.report = true
main.plugins.grid.exclude = [ "Net-Internal",]

main.plugins.eviltwinpro.enabled = true
main.plugins.eviltwinpro.interface = "wlan0mon"
main.plugins.eviltwinpro.max_attempts = 3
main.plugins.eviltwinpro.deauth_packets = 10
main.plugins.eviltwinpro.attack_duration = 120
main.plugins.eviltwinpro.captive_portal_enabled = true
main.plugins.eviltwinpro.captive_portal_path = "/etc/pwnagotchi/captive_portal"
main.plugins.eviltwinpro.ui.position = [
 0,
 0,
]

main.plugins.fake_ap_spammer.enabled = false
main.plugins.fake_ap_spammer.max_ssids = 50
main.plugins.fake_ap_spammer.ssid_length = 8
main.plugins.fake_ap_spammer.common_ratio = 0.3

main.plugins.auto-update.enabled = true
main.plugins.auto-update.install = true
main.plugins.auto-update.interval = 1

main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.devices.android-phone.enabled = false
main.plugins.bt-tether.devices.android-phone.search_order = 1
main.plugins.bt-tether.devices.android-phone.mac = ""
main.plugins.bt-tether.devices.android-phone.ip = "192.168.44.44"
main.plugins.bt-tether.devices.android-phone.netmask = 24
main.plugins.bt-tether.devices.android-phone.interval = 1
main.plugins.bt-tether.devices.android-phone.scantime = 15
main.plugins.bt-tether.devices.android-phone.max_tries = 6
main.plugins.bt-tether.devices.android-phone.share_internet = true
main.plugins.bt-tether.devices.android-phone.priority = 1

main.plugins.bt-tether.devices.ios-phone.enabled = true
main.plugins.bt-tether.devices.ios-phone.search_order = 99
main.plugins.bt-tether.devices.ios-phone.mac = "74:42:18:47:5E:7C"
main.plugins.bt-tether.devices.ios-phone.ip = "175.20.10.1"
main.plugins.bt-tether.devices.ios-phone.netmask = 24
main.plugins.bt-tether.devices.ios-phone.interval = 5
main.plugins.bt-tether.devices.ios-phone.scantime = 20
main.plugins.bt-tether.devices.ios-phone.max_tries = 99
main.plugins.bt-tether.devices.ios-phone.share_internet = true
main.plugins.bt-tether.devices.ios-phone.priority = 999

main.plugins.fix_services.enabled = true

main.plugins.gdrivesync.enabled = true
main.plugins.gdrivesync.backupfiles = [ "",]
main.plugins.gdrivesync.backup_folder = "PwnagotchiBackups"

main.plugins.logtail.enabled = true
main.plugins.logtail.max-lines = 10000

main.plugins.memtemp.enabled = false
main.plugins.memtemp.scale = "celsius"
main.plugins.memtemp.orientation = "horizontal"

main.plugins.onlinehashcrack.enabled = false
main.plugins.onlinehashcrack.email = ""
main.plugins.onlinehashcrack.dashboard = ""
main.plugins.onlinehashcrack.single_files = false

main.plugins.session-stats.enabled = true
main.plugins.session-stats.save_directory = "/var/tmp/pwnagotchi/sessions/"

main.plugins.webcfg.enabled = true

main.plugins.wpa-sec.enabled = true
main.plugins.wpa-sec.api_key = "b3ee61ac95ad66bc9f90ca33a2fdffb9"
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org"
main.plugins.wpa-sec.download_results = true

main.plugins.handshakes-dl.enabled = true

main.plugins.memtemp-plus.enabled = true
main.plugins.memtemp-plus.scale = "celsius"
main.plugins.memtemp-plus.orientation = "horizontal"
main.plugins.memtemp-plus.fields = "mem,cpu,freq,temp"
main.plugins.memtemp-plus.position = "165,82"
main.plugins.memtemp-plus.linespacing = 13

main.plugins.wpa-sec-list.enabled = true

main.plugins.aircrackonly.enabled = false

main.plugins.gpio_buttons.enabled = false

main.plugins.gps.enabled = false
main.plugins.gps.speed = 19200
main.plugins.gps.device = "/dev/ttyUSB0"

main.plugins.pisugar2.enabled = false
main.plugins.pisugar2.shutdown = 5
main.plugins.pisugar2.sync_rtc_on_boot = false

main.plugins.ups_hat_c.enabled = false
main.plugins.ups_hat_c.label_on = true
main.plugins.ups_hat_c.shutdown = 5
main.plugins.ups_hat_c.bat_x_coord = 140
main.plugins.ups_hat_c.bat_y_coord = 0

main.plugins.ups_lite.enabled = false
main.plugins.ups_lite.shutdown = 2

main.plugins.webgpsmap.enabled = true

main.plugins.wigle.enabled = false
main.plugins.wigle.api_key = ""
main.plugins.wigle.donate = false

main.plugins.net-pos.enabled = false
main.plugins.net-pos.api_key = "test"

main.plugins.IPDisplay.enabled = false
main.plugins.IPDisplay.skip_devices = [ "lo",]

main.plugins.display-password.enabled = false
main.plugins.display-password.orientation = "horizontal"

main.plugins.internet-connection.enabled = true

main.plugins.cuff.enabled = false
main.plugins.cuff.whitelist = ""

main.plugins.hashieclean.enabled = false

main.plugins.better_quickdic.enabled = true
main.plugins.better_quickdic.face = "(·ω·)"
main.plugins.better_quickdic.wordlist_folder = "/home/pi/wordlists/"
main.plugins.better_quickdic.api = ""
main.plugins.better_quickdic.id = ""

main.plugins.tweak_view.enabled = true

main.plugins.exp.enabled = true
main.plugins.exp.lvl_x_coord = 156
main.plugins.exp.lvl_y_coord = 72
main.plugins.exp.exp_x_coord = 196
main.plugins.exp.exp_y_coord = 72
main.plugins.exp.bar_symbols_count = 8

main.plugins.enable_deauth.enabled = false

main.plugins.enable_assoc.enabled = true

main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugin_repos = [
 "https://github.com/jayofelony/pwnagotchi-torch-plugins/archive/master.zip",
 "https://github.com/tisboyo/pwnagotchi-pisugar2-plugin/archive/master.zip",
 "https://github.com/nullm0ose/pwnagotchi-plugin-pisugar3/archive/master.zip",
 "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
 "https://github.com/NeonLightning/pwny/archive/master.zip",
 "https://github.com/marbasec/UPSLite_Plugin_1_3/archive/master.zip",
]
main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/"
main.plugin.gdrivesync.interval = 1

main.iface = "wlan0mon"
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.mon_max_blind_epochs = 50
main.no_restart = false
main.log.path = "/etc/pwnagotchi/log/pwnagotchi.log"
main.log.rotation.enabled = true
main.log.rotation.size = "10M"

ui.display.enabled = true
ui.display.type = "waveshare_4"
ui.display.color = "white"
ui.display.rotation = 180

ui.invert = true
ui.fps = 1
ui.font.name = "DejaVuSansMono"
ui.font.size_offset = 0


ui.faces.look_r = "/custom-faces/LOOK_R.png"
ui.faces.look_l = "/custom-faces/LOOK_L.png"
ui.faces.look_r_happy = "/custom-faces/LOOK_R_HAPPY.png"
ui.faces.look_l_happy = "/custom-faces/LOOK_L_HAPPY.png"
ui.faces.sleep = "/custom-faces/SLEEP.png"
ui.faces.sleep2 = "/custom-faces/SLEEP2.png"
ui.faces.awake = "/custom-faces/AWAKE.png"
ui.faces.bored = "/custom-faces/BORED.png"
ui.faces.intense = "/custom-faces/INTENSE.png"
ui.faces.cool = "/custom-faces/COOL.png"
ui.faces.happy = "/custom-faces/HAPPY.png"
ui.faces.excited = "/custom-faces/EXCITED.png"
ui.faces.grateful = "/custom-faces/GRATEFUL.png"
ui.faces.motivated = "/custom-faces/MOTIVATED.png"
ui.faces.demotivated = "/custom-faces/DEMOTIVATED.png"
ui.faces.smart = "/custom-faces/SMART.png"
ui.faces.lonely = "/custom-faces/LONELY.png"
ui.faces.sad = "/custom-faces/SAD.png"
ui.faces.angry = "/custom-faces/ANGRY.png"
ui.faces.friend = "/custom-faces/FRIEND.png"
ui.faces.broken = "/custom-faces/BROKEN.png"
ui.faces.debug = "/custom-faces/DEBUG.png"
ui.faces.upload = "/custom-faces/UPLOAD.png"
ui.faces.upload1 = "/custom-faces/UPLOAD1.png"
ui.faces.upload2 = "/custom-faces/UPLOAD2.png"
ui.faces.png = true
ui.faces.position_x = 0
ui.faces.position_y = 34

ui.web.enabled = true
ui.web.address = "::"
ui.web.username = "changeme"
ui.web.password = "changeme"
ui.web.origin = ""
ui.web.port = 8080
ui.web.on_frame = ""

ai.enabled = true
ai.path = "/root/brain.nn"
ai.laziness = 0.08
ai.epochs_per_episode = 350
ai.params.gamma = 0.99
ai.params.n_steps = 5
ai.params.vf_coef = 0.5
ai.params.ent_coef = 0.01
ai.params.max_grad_norm = 0.5
ai.params.learning_rate = 0.0005
ai.params.verbose = 1

personality.advertise = true
personality.deauth = true
personality.associate = true
personality.channels = [
 1,
 2,
 5,
 8,
 9,
 11,
 40,
 48,
 52,
 56,
 100,
 104,
 108,
 112,
 116,
 120,
 124,
 128,
 132,
 136,
 140,
 144,
 149,
 153,
 157,
 165,
]
personality.min_rssi = -169
personality.ap_ttl = 470
personality.sta_ttl = 149
personality.recon_time = 60
personality.max_inactive_scale = 7
personality.recon_inactive_multiplier = 3
personality.hop_recon_time = 44
personality.min_recon_time = 6
personality.max_interactions = 13
personality.max_misses_for_recon = 5
personality.excited_num_epochs = 25
personality.bored_num_epochs = 6
personality.sad_num_epochs = 16
personality.bond_encounters_factor = 20000
personality.throttle_a = 0.4
personality.throttle_d = 0.9
personality.clear_on_exit = true

bettercap.handshakes = "/home/pi/handshakes"
bettercap.silence = [
 "ble.device.new",
 "ble.device.lost",
 "ble.device.disconnected",
 "ble.device.connected",
 "ble.device.service.discovered",
 "ble.device.characteristic.discovered",
 "wifi.client.new",
 "wifi.client.lost",
 "wifi.client.probe",
 "wifi.ap.new",
 "wifi.ap.lost",
 "mod.started",
]

fs.memory.enabled = true
fs.memory.mounts.log.enabled = true
fs.memory.mounts.log.mount = "/etc/pwnagotchi/log/"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true

fs.memory.mounts.data.enabled = true
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.size = "10M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = true
fs.memory.mounts.data.rsync = true

